version: '3.6'
services:
  jenkins:
    build: jenkins
    environment:
      - VIRTUAL_HOST=jenkins.local
      - VIRTUAL_PORT=8080
    volumes:
      - ${PWD}/jenkins/jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
      - /home/annil/git/citools:/citools
  httpd:
    image: jwilder/nginx-proxy
    ports:
      - 8082:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  buildserver:
    build: slave
  kazam:
    build: slave
