
security:
  globaljobdslsecurityconfiguration:
    useScriptSecurity: false

unclassified:
  managegroovyscriptsecurity:
    groovyScriptSandboxSecurityDisabled: true

jenkins:
  systemMessage: |
    <h1 id="blink">POC: Jenkins as Code</h1>
    <p>
      This is a demo of Jenkins running in a Docker container with:
      <ul>
        <li>All plugins installed automatically</li>
        <li>All configuration managed by seed and the "Configuration as Code" plugin</li>
      </ul>
    </p>

    <script type="text/javascript">
    toggleItem = function(){
        var el = document.getElementById('blink');
        if (el.style.visibility === 'hidden') {
            el.style.visibility = '';
        } else {
            el.style.visibility = 'hidden';
        }
    }

    setInterval(toggleItem, 1000);
    </script>
  
  labelString: "master"
  numExecutors: 5

  markupFormatter: unsafe
  authorizationStrategy: unsecured

  viewsTabBar: standard

  views:
    - all:
        name: 'All'
    - list:
        name: 'Admin'
        columns:
          - buildButton
          - status
          - jobNameColumn
          - lastSuccess
          - lastFailure
          - lastDuration
        includeRegex: "seed-.*"

  nodes:
    - permanent:
        name: "buildserver"
        mode: NORMAL
        nodeName: "buildserver"
        numExecutors: 10
        remoteFS: "/root"
        labelString: "default incremental release-packaging"
        launcher:
          sSHLauncher:
            host: "zmt-5212_buildserver_1"
            port: 22
            credentialsId: jenkins_ssh_key
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
    - permanent:
        name: "kazam"
        mode: NORMAL
        nodeName: "kazam"
        numExecutors: 10
        remoteFS: "/root"
        labelString: "Kazam Kazam-stub-pvr Kazam-stub-zap Kazam-stub-release stability"
        launcher:
          sSHLauncher:
            host: "zmt-5212_kazam_1"
            port: 22
            credentialsId: jenkins_ssh_key
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false

jobs:
  - script: >
      job("seed-icons") {
        label("master")
        steps {
          shell("rsync -a --delete --chown=jenkins:jenkins /citools/icons \"\${WORKSPACE}\"/")
          shell("rsync -a --delete --chown=jenkins:jenkins /citools/install \"\${WORKSPACE}\"/")
          shell("cd \"\$WORKSPACE\"/install && USER=jenkins ./configure-icons --install")
        }
      }
  - script: >
      job("seed-test-configuration") {
        label("master")
        steps {
          shell("rsync -a --delete --chown=jenkins:jenkins --exclude 'build' /citools/seed \${WORKSPACE}")
          dsl {
            external("seed/src/main/groovy/test.jdsl")
            removeAction("DELETE")
          }
        }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: jenkins_ssh_key
              username: root
              passphrase: ""
              privateKeySource:
                directEntry:
                  privateKey: |
                    -----BEGIN RSA PRIVATE KEY-----
                    MIIJKAIBAAKCAgEAnGDa2fiPaOXbnNYsFZLOCnAxw2Nq1JdFRJvZlcVkw4iNFioN
                    ozEzO5tm4E0de4gvjaWzUvAnabW9mqK10v7CW1XRANtB8wVGvHWL07Zzkxa46foj
                    qPXG5i9bXSVA/VCa6sujdtJXzOi+jpYcNmkLYD8VgPETHy3FGakJOlFFjGlTnh8J
                    k7Nm4urQFSvSiBUF5YrH+90/2bzchqxDg2G6oT4p5SBSjv/eNJkPwiwtsZbS0HHu
                    CCvRjHgAC5s3+oy03n9XIgZ4xWDqHMdm9U4BTGx0pj+8Gv4SqvVNQb6zwkZBDejK
                    EQAEK8ftkJT5sdX/HPCUv+Wgfs6GWsW5mQrQDQb3MlwddFXsc4YrVn3fRPL+Y5VT
                    HNUiEbF7avz8PxTMwSHNlDV4V33FAbjb7AYlN+Zt11aG9p3HXXfBuUJIjDVIDgWP
                    iAKnvli37NGK6aJ0X80dkyzegnfrO6LFrCrgjgNjAci5hoG/demSzWSBgVJZxzei
                    ufh+sUqFh9i7BBFdnKHgm4eeGLnoDSR2gSDEitEn/uKo35UEvpOScf1VbyNvm/wy
                    LVTssAC43Pj5xIO/fQonoutgmnk8k+sqccRdLXk2GYwGo4Ybl1BfCD8RIvmuN9FK
                    ueVgrJiKnQC1uljf+LDhWMiroefGlAc0w/pPSwSVORuxEXejtzP4jVLAEAsCAwEA
                    AQKCAgBH/IoilzqlRlLvguQuVjNFONqfoG94R96aM8hZGtJE9OJF1rwKaMa15NbZ
                    4IX27P0/Do1bW7Q5BHGw8sASzjX4R6v74fMdBUvHy7C/mBjiGC6tfvnVeLbEFf7Q
                    BStCsU1vUqkANNo4ONgn2VBJd9fFyaSDg/aSfsZiBp952hnTBlV4z77f4FE3mnKJ
                    nG/BNzRMs7NV7UbMXBWEZV565407VtuAX33B2GWY/vDzKNUsEEshq6Cw4EMJj+At
                    d5mwW/+TATnCLwp/ihqbfuuVdwBABxk3wtU788PyMRQMdNZZU2/1EDmc084XvWRO
                    D1ZWmDVlRBals/ZLCZVtyeGjYwfcjxc/DUL0zAooYTOMHP+VNRzzupWsJ9xdAFkQ
                    2A0+JDt42BmvAxx2uqJbwwv5cuOU93/z2rsqrMrNDwGmgx0/GhoRPoi42ksPUSK+
                    fyd+mfyLEDNF3xTChTT2LrL57ntmTVBIjkZz9OTpehy+Holfc4qr+DHtPcMnAbc5
                    lpH8gls7ZDvhJQG7gNGtWMKlcVitrWKrxVAQSan8Jjns3widn6JCXMHPYmF1Jt5k
                    D3F+A0DILmdH+SXZw9As6Rd/P/I4SELwO1bn0igaN8QeKnaLRSrjViGDVun8L7r0
                    rAJjgRAVkO4AZbOD/wbxOyijJsQio+L7+dI4rfG1ebtdRrX0IQKCAQEAzU4Rwvns
                    16duVcnrvuOrri3YViZrWm8v/lMzn9LXPaDORq0+0Q9f7UHd3iLPfYZVSlvW/Ra/
                    pCCkASRyJmYCjnO5bRJaL0QJ9joRTtep7VEFaeqrp5oinG68V96GqaW+WZYKwEF3
                    UpwLpd4iuYiOga1ThMLAEYEfuzDRf3v4SfAsNUqpSKtmkWxjqjiYJO1TgHrz+PV3
                    IAZqYiIjbNj1v14kFG/nZwVGt2F06FUP/IpUTxlamMzAQWyw2SaP53tRxMWpur/W
                    DCWj2X9EjRT3L7M2/h3gRWo6k2+neIdjUoqFGXG+KNjotiI8PQOgCn7T95fhn1Ah
                    IMU5oiduWIQ+0QKCAQEAwv39a95P8m2t67Uu+CTYWlL3x9j+g9D49gxHv5wyPery
                    5uqtuEkUbEc+7aO7cYF76sQM3kMegwLRt3RsjJD7PpmmaqIqBirqDdbmNi+snYNd
                    zzD8bQkZEBevkdUGSFtdD2SYE0MzcscSiEivsomRSH0BR+yU/IyEj6jtuhhioCIZ
                    J65QQhAyH66ZaSKTk7Jc+1wFfaOT0gSeRR/fKIAZtLc5i4UKVXRIlsaZ/J8O9euN
                    Soih115/AogrbJpt/2OQ7R7lJy7UZD82QU1Uh6ULO4HO/2lbPweaLzNpNytMOjE/
                    NdJy/ayB1GdJjwgtlwLDigTEiyZ6Td8DVxtaNLJwGwKCAQAiMWVt5rgWdrE+ooGb
                    6kk2mjYUqxNoHWqN3geUD8Z/Yh/Yz5PNt9TPLBAqpfuOuWfNGZylzDsgt7r44bwN
                    PyIf3ZA9ZTgV9Sv/kU4+plaLytmu+UGbiWVITn0Z2VruOEeKnh2uRXj9DjY2ate3
                    tNGfMWHek5zvjWTehVPu+pOwpMqIGaY2Dy3m/Hlg6UoVpF0q4c9uYFt1vvvK2kqy
                    HzRWqfQyXyzYEJ3lftq8syYVdmhyQBPBrSA8BUEy+WQwNm646f7JtpeMsFwopjSh
                    lqNQk3WOPyWSCg41bfwja9ET9zQRt8rm/LFNXEhSFR97gAIHk4klQnAyCAcARbbw
                    ER5xAoIBADDMQWyKUTWZTyoqyJtfFSndk5bW7jLszDE/N4FzRHuMXcd+OYVh/JNw
                    bQYpsJIiVnGVKKdC4tLklLk1kKjI66dp6mTLOnsaqEJYYnpzCd7Nbl+YocNjwHrv
                    goebaRwYiTx97zT631g9C51Bm36xwMMETZrDUTG2tMIDA6NL0PrELclpbTprNTAK
                    kOfnuEkBHRXmnJUpp6eqcjVYWY+YJ1a7d9I7tC9Yj4X0I7s9zw+qKEzbzqzIQD7Q
                    9xURvK9qKm29Cpn4tTx1OU20XZAotJvqy3PN2QD4FRT058Lfug7iHjCI/zAOyNrw
                    Ek+SO16MWYUj1lAAjCEKy5o0BSok8bsCggEBAMPscRnOQM8aE1cknTg4mab2R8TR
                    W9aqQPgzhadOjJhDgbtUVR66FX+PRWqDI7Y/3UxRqjO3BFSGt8bsaKhx4VKTGPP7
                    +9tbRZGJNPb58ffM7bqZeT9TNFFsl0UrniduEtkB+j0WMixH21kcxoUiAtiz4O80
                    TV3NK7R4Siusnr9AIRYJdA289XmGvNjkYtV+Hqr1g8XKSca7SOMiEVPNwznhveup
                    jEIifcXXEQmnm9kL5cbhPPjuSFzXwdECCLYlfeW9EWLx8E1o1XorW1iAZO8Gvw0r
                    sTiIwJCD+F+xtKxvIrCpFav41JmzM7lORUmEb9RpTiVLGPTWPxbikfeCtx4=
                    -----END RSA PRIVATE KEY-----
